=== Crystal3003/I2P_114062111/schemas/skill.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "required": ["id", "name", "ec", "effects"],
  "properties": {
    "id": {
      "type": "string",
      "pattern": "^[a-z0-9_]+$",
      "description": "Unique skill id"
    },
    "name": {
      "type": "string"
    },
    "ec": {
      "type": "integer",
      "minimum": 0
    },
    "effects": {
      "type": "array",
      "minItems": 1,
      "items": {
        "$ref": "#/definitions/effect"
      }
    }
  },
  "definitions": {
    "effect": {
        "oneOf": [
            {
            "type": "object",
            "required": ["type", "target", "element", "power"],
            "properties": {
                "type": { "const": "attack" },
                "target": { "enum": ["self", "enemy"] },
                "element": {
                "enum": ["grass", "fire", "water", "dark", "divine", "neutral"]
                },
                "power": {
                "type": "number",
                "minimum": 0
                },
                "chance": {
                "type": "number",
                "minimum": 0,
                "maximum": 1
                }
            },
            "additionalProperties": false
            },

            {
            "type": "object",
            "required": ["type", "target", "method", "value"],
            "properties": {
                "type": { "const": "heal" },
                "target": { "enum": ["self", "enemy"] },
                "method": {
                "enum": ["add", "lost_hp", "max_hp"]
                },
                "value": {
                "type": "number",
                "minimum": 0
                },
                "chance": {
                "type": "number",
                "minimum": 0,
                "maximum": 1
                }
            },
            "additionalProperties": false
            },
            
            {
            "type": "object",
            "required": ["type", "id", "target", "method", "value", "duration"],
            "properties": {
                "type": { "const": "apply_effect" },
                "target": { "enum": ["self", "enemy"] },
                "id": {
                    "enum": ["attack_up", "attack_down", "defense_up", "defense_down", "speed_up", "speed_down"]
                },
                "method": {
                "enum": ["add", "multiply"]
                },
                "value": {
                "type": "number",
                "minimum": 0
                },
                "duration":{
                    "type": "number",
                    "minimum": 1
                },
                "chance": {
                "type": "number",
                "minimum": 0,
                "maximum": 1
                }
            },
            "additionalProperties": false
            },

            {
            "type": "object",
            "required": ["type", "id", "target", "duration"],
            "properties": {
                "type": { "const": "apply_status" },
                "target": { "enum": ["self", "enemy"] },
                "id": {
                    "enum": ["bleed", "regen", "on_fire", "thorn", "invincible", 
                    "vulnerable", "poison", "stun", "sleep"]
                },
                "duration":{
                    "type":"number",
                    "minimum": 1
                },
                "chance": {
                "type": "number",
                "minimum": 0,
                "maximum": 1
                }
            },
            "additionalProperties": false
            },

            {
            "type": "object",
            "required": ["type", "id", "target"],
            "properties": {
                "type": { "const": "special" },
                "id": {
                    "enum": ["additional_energy", "eliminate_dark", "purify", "tunnel_escape"]
                },
                "chance": {
                "type": "number",
                "minimum": 0,
                "maximum": 1
                },
                "value":{
                    "type": "number",
                    "description": "for additional_energy"
                },
                "target":{
                  "type": "string",
                  "enum": ["self", "enemy"]
                }
            },
            "additionalProperties": false
            }
        ]
    }

    }

}

=== Crystal3003/I2P_114062111/monster_info/moves/shadow_scratch.json
{
    "id": "shadow_scratch",
    "name": "Shadow Scratch",
    "ec": 2,
    
    "effects":[
        {
            "type": "attack",
            "target": "enemy",
            "element": "dark",
            "power": 1.0
        },
        {
            "type": "attack",
            "target":"enemy",
            "element": "neutral",
            "power": 0.5
        }
    ]
}

=== Crystal3003/I2P_114062111/monster_info/moves/bloomstorm.json
{
    "id": "bloomstorm",
    "name": "Bloomstorm",
    "ec": 8,
    
    "effects":[
        {
            "type": "attack",
            "target": "enemy",
            "element": "grass",
            "power": 0.8
        },
        {
            "type": "attack",
            "target": "enemy",
            "element": "grass",
            "power": 0.8
        },
        {
            "type": "attack",
            "target": "enemy",
            "element": "grass",
            "power": 0.8
        },
        {
            "type": "apply_status",
            "id": "vulnerable",
            "target": "enemy",
            "duration": 3
        }
    ]
}

=== Crystal3003/I2P_114062111/monster_info/moves/ancient_vine.json
{
    "id": "ancient_vine",
    "name": "Ancient Vine",
    "ec": 1,
    
    "effects":[
        {
            "type": "attack",
            "target": "enemy",
            "element": "grass",
            "power": 1.0
        },
        {
            "type": "attack",
            "target":"enemy",
            "element": "neutral",
            "power": 0.2
        }
    ]
}

=== Crystal3003/I2P_114062111/monster_info/moves/radiant_horn.json
{
    "id": "radiant_horn",
    "name": "Radiant Horn",
    "ec": 1,
    
    "effects":[
        {
            "type": "attack",
            "target": "enemy",
            "element": "divine",
            "power": 1.0
        },
        {
            "type": "special",
            "id": "additional_energy",
            "target": "self",
            "value": 2
        }
    ]
}

=== Crystal3003/I2P_114062111/monster_info/moves/venom_of_dread.json
{
    "id": "venom_of_dread",
    "name": "Venom of Dread",
    "ec": 2,
    
    "effects":[
        {
            "type": "attack",
            "target": "enemy",
            "element": "dark",
            "power": 1.0
        },
        {
            "type": "apply_status",
            "id": "poison",
            "target": "enemy",
            "duration": 1
        }
    ]
}

=== Crystal3003/I2P_114062111/monster_info/moves/peck_flurry.json
{
    "id": "peck_flurry",
    "name": "Peck Flurry",
    "ec": 1,
    
    "effects":[
        {
            "type": "attack",
            "target": "enemy",
            "element": "neutral",
            "power": 0.7
        },
        {
            "type": "attack",
            "target": "enemy",
            "element": "neutral",
            "power": 0.7
        }
    ]
}

=== Crystal3003/I2P_114062111/monster_info/moves/umbral_bind.json
{
    "id": "umbral_bind",
    "name": "Umbral Bind",
    "ec": 1,
    
    "effects":[
        {
            "type": "attack",
            "target": "enemy",
            "element": "dark",
            "power": 1.1
        },
        {
            "type": "apply_effect",
            "id": "defense_down",
            "target": "enemy",
            "method": "multiply",
            "value": 0.75,
            "duration": 2,
            "chance": 0.25
        }
    ]
}

=== Crystal3003/I2P_114062111/monster_info/moves/cataclysm_breath.json
{
    "id": "cataclysm_breath",
    "name": "Cataclysm Breath",
    "ec": 12,
    
    "effects":[
        {
            "type": "attack",
            "element": "fire",
            "power": 1.5,
            "target": "enemy"
        },
        {
            "type": "apply_status",
            "id": "on_fire",
            "duration": 2,
            "target": "enemy"
        },
        {
            "type": "apply_effect",
            "id": "defense_down",
            "method": "multiply",
            "value": 0.5,
            "duration": 2,
            "target": "enemy"
        }
    ]
}
