=== Crystal3003/I2P_114062111/schemas/skill.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "required": ["id", "name", "ec", "effects"],
  "properties": {
    "id": {
      "type": "string",
      "pattern": "^[a-z0-9_]+$",
      "description": "Unique skill id"
    },
    "name": {
      "type": "string"
    },
    "ec": {
      "type": "integer",
      "minimum": 0
    },
    "effects": {
      "type": "array",
      "minItems": 1,
      "items": {
        "$ref": "#/definitions/effect"
      }
    }
  },
  "definitions": {
    "effect": {
        "oneOf": [
            {
            "type": "object",
            "required": ["type", "target", "element", "power"],
            "properties": {
                "type": { "const": "attack" },
                "target": { "enum": ["self", "enemy"] },
                "element": {
                "enum": ["grass", "fire", "water", "dark", "divine", "neutral"]
                },
                "power": {
                "type": "number",
                "minimum": 0
                },
                "chance": {
                "type": "number",
                "minimum": 0,
                "maximum": 1
                }
            },
            "additionalProperties": false
            },

            {
            "type": "object",
            "required": ["type", "target", "method", "value"],
            "properties": {
                "type": { "const": "heal" },
                "target": { "enum": ["self", "enemy"] },
                "method": {
                "enum": ["add", "lost_hp", "max_hp"]
                },
                "value": {
                "type": "number",
                "minimum": 0
                },
                "chance": {
                "type": "number",
                "minimum": 0,
                "maximum": 1
                }
            },
            "additionalProperties": false
            },
            
            {
            "type": "object",
            "required": ["type", "id", "target", "method", "value", "duration"],
            "properties": {
                "type": { "const": "apply_effect" },
                "target": { "enum": ["self", "enemy"] },
                "id": {
                    "enum": ["attack_up", "attack_down", "defense_up", "defense_down", "speed_up", "speed_down"]
                },
                "method": {
                "enum": ["add", "multiply"]
                },
                "value": {
                "type": "number",
                "minimum": 0
                },
                "duration":{
                    "type": "number",
                    "minimum": 1
                },
                "chance": {
                "type": "number",
                "minimum": 0,
                "maximum": 1
                }
            },
            "additionalProperties": false
            },

            {
            "type": "object",
            "required": ["type", "id", "target", "duration"],
            "properties": {
                "type": { "const": "apply_status" },
                "target": { "enum": ["self", "enemy"] },
                "id": {
                    "enum": ["bleed", "regen", "on_fire", "thorn", "invincible", 
                    "vulnerable", "poison", "stun", "sleep"]
                },
                "duration":{
                    "type":"number",
                    "minimum": 1
                },
                "chance": {
                "type": "number",
                "minimum": 0,
                "maximum": 1
                }
            },
            "additionalProperties": false
            },

            {
            "type": "object",
            "required": ["type", "id", "target"],
            "properties": {
                "type": { "const": "special" },
                "id": {
                    "enum": ["additional_energy", "eliminate_dark", "purify", "tunnel_escape"]
                },
                "chance": {
                "type": "number",
                "minimum": 0,
                "maximum": 1
                },
                "value":{
                    "type": "number",
                    "description": "for additional_energy"
                },
                "target":{
                  "type": "string",
                  "enum": ["self", "enemy"]
                }
            },
            "additionalProperties": false
            }
        ]
    }

    }

}

=== Crystal3003/I2P_114062111/monster_info/moves/verdant_cyclone.json
{
    "id": "verdant_cyclone",
    "name": "Verdant Cyclone",
    "ec": 2,
    
    "effects":[
        {
            "type": "attack",
            "target": "enemy",
            "element": "grass",
            "power": 0.8
        },
        {
            "type": "attack",
            "target": "enemy",
            "element": "grass",
            "power": 0.7,
            "chance": 0.6
        },
        {
            "type": "attack",
            "target": "enemy",
            "element": "grass",
            "power": 0.7,
            "chance": 0.6
        }
    ]
}

=== Crystal3003/I2P_114062111/monster_info/moves/pollen_puff.json
{
    "id": "pollen_puff",
    "name": "Pollen Puff",
    "ec": 6,
    
    "effects":[
        {
            "type": "attack",
            "target": "enemy",
            "element": "grass",
            "power": 1.2
        },
        {
            "type": "apply_effect",
            "id": "attack_down",
            "target": "enemy",
            "method": "multiply",
            "value": 0.8,
            "duration": 2
        }
    ]
}

=== Crystal3003/I2P_114062111/monster_info/moves/natures_resurgence.json
{
    "id": "natures_resurgence",
    "name": "Nature's Resurgence",
    "ec": 5,
    
    "effects":[
        {
            "type": "heal",
            "target": "self",
            "method": "lost_hp",
            "value": 0.25
        },
        {
            "type": "apply_status",
            "id": "regen",
            "target": "self",
            "duration": 2
        }
    ]
}

=== Crystal3003/I2P_114062111/monster_info/moves/headbutt.json
{
    "id": "headbutt",
    "name": "Headbutt",
    "ec": 3,
    
    "effects":[
        {
            "type": "attack",
            "target": "enemy",
            "element": "neutral",
            "power": 1.5
        },
        {
            "type": "apply_status",
            "id": "stun",
            "duration": 1,
            "target": "enemy",
            "chance": 0.2
        }
    ]
}

=== Crystal3003/I2P_114062111/monster_info/moves/pollen_shot.json
{
    "id": "pollen_shot",
    "name": "Pollen Shot",
    "ec": 2,
    
    "effects":[
        {
            "type": "attack",
            "target": "enemy",
            "element": "grass",
            "power": 1.0
        },
        {
            "type": "apply_effect",
            "id": "defense_down",
            "method": "add",
            "value": 15,
            "duration": 2,
            "target": "enemy"
        }
    ]
}

=== Crystal3003/I2P_114062111/monster_info/moves/smolder_hide.json
{
    "id": "smolder_hide",
    "name": "Smolde Hide",
    "ec": 1,
    
    "effects":[
        {
            "type": "apply_effect",
            "id": "defense_up",
            "target": "self",
            "method": "add",
            "value": 7,
            "duration": 1
        },
        {
            "type": "attack",
            "target": "enemy",
            "element": "fire",
            "power": 0.5
        }
    ]
}

=== Crystal3003/I2P_114062111/monster_info/moves/ash_devour.json
{
    "id": "ash_devour",
    "name": "Ash Devour",
    "ec": 2,
    
    "effects":[
        {
            "type": "attack",
            "target": "enemy",
            "element": "fire",
            "power": 0.75
        },
        {
            "type": "apply_effect",
            "id": "attack_up",
            "chance": 0.5,
            "method": "multiply",
            "value": 1.5,
            "duration": 1,
            "target": "self"
        },
        {
            "type": "heal",
            "chance": 0.25,
            "method": "add",
            "value": 50,
            "target": "self"
        }
    ]
}

=== Crystal3003/I2P_114062111/monster_info/moves/volcanic_carapace.json
{
    "id": "volcanic_carapace",
    "name": "Volcanic Carapace",
    "ec": 1,
    
    "effects":[
        {
            "type": "apply_effect",
            "id": "defense_up",
            "method": "add",
            "value": 75,
            "duration": 1,
            "target": "self"
        },
        {
            "type": "apply_status",
            "id": "thorn",
            "duration": 1,
            "target": "self"
        }
    ]
}
