=== Crystal3003/I2P_114062111/schemas/skill.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "required": ["id", "name", "ec", "effects"],
  "properties": {
    "id": {
      "type": "string",
      "pattern": "^[a-z0-9_]+$",
      "description": "Unique skill id"
    },
    "name": {
      "type": "string"
    },
    "ec": {
      "type": "integer",
      "minimum": 0
    },
    "effects": {
      "type": "array",
      "minItems": 1,
      "items": {
        "$ref": "#/definitions/effect"
      }
    }
  },
  "definitions": {
    "effect": {
        "oneOf": [
            {
            "type": "object",
            "required": ["type", "target", "element", "power"],
            "properties": {
                "type": { "const": "attack" },
                "target": { "enum": ["self", "enemy"] },
                "element": {
                "enum": ["grass", "fire", "water", "dark", "divine", "neutral"]
                },
                "power": {
                "type": "number",
                "minimum": 0
                },
                "chance": {
                "type": "number",
                "minimum": 0,
                "maximum": 1
                }
            },
            "additionalProperties": false
            },

            {
            "type": "object",
            "required": ["type", "target", "method", "value"],
            "properties": {
                "type": { "const": "heal" },
                "target": { "enum": ["self", "enemy"] },
                "method": {
                "enum": ["add", "lost_hp", "max_hp"]
                },
                "value": {
                "type": "number",
                "minimum": 0
                },
                "chance": {
                "type": "number",
                "minimum": 0,
                "maximum": 1
                }
            },
            "additionalProperties": false
            },
            
            {
            "type": "object",
            "required": ["type", "id", "target", "method", "value", "duration"],
            "properties": {
                "type": { "const": "apply_effect" },
                "target": { "enum": ["self", "enemy"] },
                "id": {
                    "enum": ["attack_up", "attack_down", "defense_up", "defense_down", "speed_up", "speed_down"]
                },
                "method": {
                "enum": ["add", "multiply"]
                },
                "value": {
                "type": "number",
                "minimum": 0
                },
                "duration":{
                    "type": "number",
                    "minimum": 1
                },
                "chance": {
                "type": "number",
                "minimum": 0,
                "maximum": 1
                }
            },
            "additionalProperties": false
            },

            {
            "type": "object",
            "required": ["type", "id", "target", "duration"],
            "properties": {
                "type": { "const": "apply_status" },
                "target": { "enum": ["self", "enemy"] },
                "id": {
                    "enum": ["bleed", "regen", "on_fire", "thorn", "invincible", 
                    "vulnerable", "poison", "stun", "sleep"]
                },
                "duration":{
                    "type":"number",
                    "minimum": 1
                },
                "chance": {
                "type": "number",
                "minimum": 0,
                "maximum": 1
                }
            },
            "additionalProperties": false
            },

            {
            "type": "object",
            "required": ["type", "id", "target"],
            "properties": {
                "type": { "const": "special" },
                "id": {
                    "enum": ["additional_energy", "eliminate_dark", "purify", "tunnel_escape"]
                },
                "chance": {
                "type": "number",
                "minimum": 0,
                "maximum": 1
                },
                "value":{
                    "type": "number",
                    "description": "for additional_energy"
                },
                "target":{
                  "type": "string",
                  "enum": ["self", "enemy"]
                }
            },
            "additionalProperties": false
            }
        ]
    }

    }

}

=== Crystal3003/I2P_114062111/monster_info/moves/furnace_roar.json
{
    "id": "furnace_roar",
    "name": "Furnace Raor",
    "ec": 8,
    
    "effects":[
        {
            "type": "attack",
            "element": "fire",
            "power": 1.25,
            "target": "enemy"
        },
        {
            "type": "apply_status",
            "id": "on_fire",
            "target": "enemy",
            "duration": 2 
        }
    ]
}

=== Crystal3003/I2P_114062111/monster_info/moves/fear_purr.json
{
    "id": "fear_purr",
    "name": "Fear Purr",
    "ec": 6,
    
    "effects":[
        {
            "type": "apply_effect",
            "id": "defense_down",
            "method": "multiply",
            "value": 0.5,
            "duration": 1,
            "target": "self"
        },
        {
            "type": "apply_effect",
            "id": "attack_up",
            "method": "multiply",
            "target": "self",
            "value": 2.0,
            "duration": 1
        }
    ]
}

=== Crystal3003/I2P_114062111/monster_info/moves/grace_step.json
{
    "id": "grace_step",
    "name": "Grace Step",
    "ec": 2,
    
    "effects":[
        {
            "type": "attack",
            "target": "enemy",
            "element": "divine",
            "power": 1.0
        },
        {
            "type": "attack",
            "target": "enemy",
            "power": 0.75,
            "element": "neutral",
            "chance": 0.5
        },
        {
            "type": "attack",
            "target": "enemy",
            "power": 0.75,
            "element": "neutral",
            "chance": 0.5
        }
    ]
}

=== Crystal3003/I2P_114062111/monster_info/moves/nactar_drain.json
{
    "id": "nectar_drain",
    "name": "Nectar Drain",
    "ec": 4,
    
    "effects":[
        {
            "type": "apply_status",
            "id": "regen",
            "target": "self",
            "duration": 2
        },
        {
            "type": "apply_status",
            "id": "poison",
            "target": "enemy",
            "duration": 2
        }
    ]
}

=== Crystal3003/I2P_114062111/monster_info/moves/inferno_rempage.json
{
    "id": "inferno_rempage",
    "name": "Inferno Rempage",
    "ec": 3,
    
    "effects":[
        {
            "type": "apply_effect",
            "id": "attack_up",
            "method": "add",
            "value": 100,
            "duration": 2,
            "target": "self"
        },
        {
            "type": "apply_effect",
            "id": "speed_up",
            "method": "add",
            "value": 10,
            "duration": 2,
            "target": "self"
        }
    ]
}

=== Crystal3003/I2P_114062111/monster_info/moves/divine_verdict.json
{
    "id": "divine_verdict",
    "name": "Divine Verdict",
    "ec": 15,
    
    "effects":[
        {
            "type": "attack",
            "target": "enemy",
            "element": "divine",
            "power": 2.0
        },
        {
            "type": "special",
            "id": "eliminate_dark",
            "target": "enemy"
        }
    ]
}

=== Crystal3003/I2P_114062111/monster_info/moves/riptide_grip.json
{
    "id": "riptide_grip",
    "name": "Riptide Grip",
    "ec": 2,
    
    "effects":[
        {
            "type": "attack",
            "target": "enemy",
            "element": "water",
            "power": 0.8
        },
        {
            "type": "heal",
            "method": "lost_hp",
            "value": 0.4,
            "target": "self"
        }
    ]
}

=== Crystal3003/I2P_114062111/monster_info/moves/verdant_roar.json
{
    "id": "verdant_roar",
    "name": "Verdant Roar",
    "ec": 7,
    
    "effects":[
        {
            "type": "attack",
            "target": "enemy",
            "element": "grass",
            "power": 1.3
        },
        {
            "type": "apply_effect",
            "id": "defense_down",
            "target": "enemy",
            "method": "multiply",
            "value": 0.75,
            "duration": 3
        },
        {
            "type": "apply_effect",
            "id": "speed_down",
            "target": "enemy",
            "method": "add",
            "value": 10,
            "duration": 3
        }
    ]
}
